import { demoListingImageSets } from './demoListingImages';

export type DemoOwner = {
  id: string;
  email: string | null;
  first_name: string | null;
  last_name: string | null;
};

export const MIN_DEMO_HOSTS = 3;
export const DEMO_LISTING_COUNT = 60;

type DemoListingTemplate = {
  id: string;
  name: string;
  categoryId: string;
  roomType: string;
  propertyType: string;
  price: number;
  smartLocation: string;
  city: string;
  country: string;
  neighborhood: string;
  latitude: number;
  longitude: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  guests: number;
  description: string;
};

const amenitySets = [
  ['Wifi', 'Kitchen', 'Washer', 'Air conditioning', 'Dedicated workspace', 'Self check-in'],
  ['Wifi', 'Free parking', 'Mountain view', 'Fireplace', 'BBQ grill', 'Patio'],
  ['Wifi', 'Pool', 'Sea view', 'Balcony', 'Kitchen', 'Air conditioning'],
  ['Wifi', 'Elevator', 'City view', 'Coffee maker', 'Washer', 'Smart TV'],
  ['Wifi', 'Garden', 'Outdoor dining', 'Heating', 'Kitchen', 'Private entrance'],
];

const demoTemplates: DemoListingTemplate[] = [
  {
    id: 'baku-old-city-micro-loft',
    name: 'Old City Micro Loft',
    categoryId: 'tiny-homes',
    roomType: 'Entire tiny home',
    propertyType: 'Tiny home',
    price: 74,
    smartLocation: 'Icherisheher, Baku, Azerbaijan',
    city: 'Baku',
    country: 'Azerbaijan',
    neighborhood: 'Icherisheher',
    latitude: 40.3661,
    longitude: 49.8372,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Compact loft inside the old city walls with a bright sleeping nook, fast wifi, and easy walks to the boulevard.',
  },
  {
    id: 'sheki-garden-tiny-home',
    name: 'Sheki Garden Tiny Home',
    categoryId: 'tiny-homes',
    roomType: 'Entire tiny home',
    propertyType: 'Tiny home',
    price: 58,
    smartLocation: 'Historic Sheki, Azerbaijan',
    city: 'Sheki',
    country: 'Azerbaijan',
    neighborhood: 'Old Sheki',
    latitude: 41.1919,
    longitude: 47.1706,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Small garden hideaway near caravanserai streets, built for quiet mornings, tea outside, and weekend escapes.',
  },
  {
    id: 'tbilisi-courtyard-studio',
    name: 'Tbilisi Courtyard Studio',
    categoryId: 'tiny-homes',
    roomType: 'Entire studio',
    propertyType: 'Studio',
    price: 66,
    smartLocation: 'Sololaki, Tbilisi, Georgia',
    city: 'Tbilisi',
    country: 'Georgia',
    neighborhood: 'Sololaki',
    latitude: 41.6897,
    longitude: 44.8015,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Warm courtyard studio with tall windows, a small kitchen, and quick access to cafes and old town lanes.',
  },
  {
    id: 'bakuriani-a-frame-tiny',
    name: 'Bakuriani A-Frame Tiny Cabin',
    categoryId: 'tiny-homes',
    roomType: 'Entire cabin',
    propertyType: 'A-frame',
    price: 92,
    smartLocation: 'Bakuriani, Georgia',
    city: 'Bakuriani',
    country: 'Georgia',
    neighborhood: 'Didveli',
    latitude: 41.7499,
    longitude: 43.5322,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'A-frame tiny cabin surrounded by pine trees with a compact kitchen and cozy loft sleeping area.',
  },
  {
    id: 'cappadocia-stone-mini-suite',
    name: 'Cappadocia Stone Mini Suite',
    categoryId: 'tiny-homes',
    roomType: 'Entire guest suite',
    propertyType: 'Stone suite',
    price: 88,
    smartLocation: 'Goreme, Cappadocia, Turkiye',
    city: 'Goreme',
    country: 'Turkiye',
    neighborhood: 'Goreme',
    latitude: 38.6431,
    longitude: 34.8289,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Minimal stone suite with sunrise balloon views, soft lighting, and a peaceful terrace for breakfast.',
  },
  {
    id: 'porto-river-tiny-flat',
    name: 'Porto River Tiny Flat',
    categoryId: 'tiny-homes',
    roomType: 'Entire flat',
    propertyType: 'Apartment',
    price: 79,
    smartLocation: 'Ribeira, Porto, Portugal',
    city: 'Porto',
    country: 'Portugal',
    neighborhood: 'Ribeira',
    latitude: 41.1407,
    longitude: -8.611,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Efficient riverside flat with exposed stone, a small dining corner, and short walks to bridges and wine cellars.',
  },
  {
    id: 'amsterdam-canal-micro-apartment',
    name: 'Amsterdam Canal Micro Apartment',
    categoryId: 'tiny-homes',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 116,
    smartLocation: 'Jordaan, Amsterdam, Netherlands',
    city: 'Amsterdam',
    country: 'Netherlands',
    neighborhood: 'Jordaan',
    latitude: 52.3731,
    longitude: 4.8812,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Clever canal apartment with built-in storage, warm wood finishes, and a quiet street near galleries.',
  },
  {
    id: 'copenhagen-harbor-tiny-home',
    name: 'Copenhagen Harbor Tiny Home',
    categoryId: 'tiny-homes',
    roomType: 'Entire home',
    propertyType: 'Tiny home',
    price: 124,
    smartLocation: 'Christianshavn, Copenhagen, Denmark',
    city: 'Copenhagen',
    country: 'Denmark',
    neighborhood: 'Christianshavn',
    latitude: 55.6724,
    longitude: 12.5945,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Scandinavian tiny home near the harbor with calm interiors, smart storage, and bikes close by.',
  },
  {
    id: 'kyoto-tea-garden-cabin',
    name: 'Kyoto Tea Garden Cabin',
    categoryId: 'tiny-homes',
    roomType: 'Entire cabin',
    propertyType: 'Cabin',
    price: 109,
    smartLocation: 'Higashiyama, Kyoto, Japan',
    city: 'Kyoto',
    country: 'Japan',
    neighborhood: 'Higashiyama',
    latitude: 35.0037,
    longitude: 135.7786,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Quiet wooden cabin near temple paths with a compact tea corner, garden view, and soft morning light.',
  },
  {
    id: 'gabala-pine-cabin',
    name: 'Gabala Pine Cabin',
    categoryId: 'cabins',
    roomType: 'Entire cabin',
    propertyType: 'Cabin',
    price: 145,
    smartLocation: 'Gabala, Azerbaijan',
    city: 'Gabala',
    country: 'Azerbaijan',
    neighborhood: 'Vandam',
    latitude: 40.981,
    longitude: 47.845,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Wood cabin under tall pines with a fireplace, mountain air, and a deck made for slow evenings.',
  },
  {
    id: 'quba-river-cabin',
    name: 'Quba River Cabin',
    categoryId: 'cabins',
    roomType: 'Entire cabin',
    propertyType: 'Cabin',
    price: 132,
    smartLocation: 'Quba, Azerbaijan',
    city: 'Quba',
    country: 'Azerbaijan',
    neighborhood: 'Qechresh',
    latitude: 41.3611,
    longitude: 48.5134,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Riverside cabin with warm interiors, outdoor seating, and quick access to forest walking routes.',
  },
  {
    id: 'shahdag-alpine-lodge',
    name: 'Shahdag Alpine Lodge',
    categoryId: 'cabins',
    roomType: 'Entire chalet',
    propertyType: 'Chalet',
    price: 188,
    smartLocation: 'Shahdag, Azerbaijan',
    city: 'Shahdag',
    country: 'Azerbaijan',
    neighborhood: 'Mountain Resort',
    latitude: 41.3166,
    longitude: 48.1323,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 7,
    description: 'Alpine lodge with big windows, ski storage, and a relaxed living room after mountain days.',
  },
  {
    id: 'borjomi-forest-chalet',
    name: 'Borjomi Forest Chalet',
    categoryId: 'cabins',
    roomType: 'Entire chalet',
    propertyType: 'Chalet',
    price: 118,
    smartLocation: 'Borjomi, Georgia',
    city: 'Borjomi',
    country: 'Georgia',
    neighborhood: 'Likani',
    latitude: 41.8389,
    longitude: 43.3792,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Forest chalet with a private balcony, mineral-spring walks nearby, and plenty of quiet.',
  },
  {
    id: 'lake-bled-wood-cabin',
    name: 'Lake Bled Wood Cabin',
    categoryId: 'cabins',
    roomType: 'Entire cabin',
    propertyType: 'Cabin',
    price: 174,
    smartLocation: 'Bled, Slovenia',
    city: 'Bled',
    country: 'Slovenia',
    neighborhood: 'Mlino',
    latitude: 46.3658,
    longitude: 14.1036,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 4,
    description: 'Wood cabin close to the lake with mountain views, a sunny deck, and simple modern comfort.',
  },
  {
    id: 'dolomites-view-cabin',
    name: 'Dolomites View Cabin',
    categoryId: 'cabins',
    roomType: 'Entire cabin',
    propertyType: 'Cabin',
    price: 210,
    smartLocation: 'Cortina d Ampezzo, Italy',
    city: 'Cortina d Ampezzo',
    country: 'Italy',
    neighborhood: 'Pocol',
    latitude: 46.5389,
    longitude: 12.1357,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    description: 'Mountain cabin with dramatic Dolomites views, a full kitchen, and a warm lounge for groups.',
  },
  {
    id: 'lapland-glass-cabin',
    name: 'Lapland Glass Cabin',
    categoryId: 'cabins',
    roomType: 'Entire cabin',
    propertyType: 'Glass cabin',
    price: 238,
    smartLocation: 'Saariselka, Finland',
    city: 'Saariselka',
    country: 'Finland',
    neighborhood: 'Kaunispaa',
    latitude: 68.4213,
    longitude: 27.4143,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Glass-roof cabin designed for northern lights, with heated floors and a quiet snowy setting.',
  },
  {
    id: 'aspen-creek-cabin',
    name: 'Aspen Creek Cabin',
    categoryId: 'cabins',
    roomType: 'Entire cabin',
    propertyType: 'Cabin',
    price: 265,
    smartLocation: 'Aspen, Colorado, United States',
    city: 'Aspen',
    country: 'United States',
    neighborhood: 'West End',
    latitude: 39.1911,
    longitude: -106.8175,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    description: 'Creekside cabin with vaulted ceilings, a stone fireplace, and easy access to trails and town.',
  },
  {
    id: 'carpathian-mountain-cabin',
    name: 'Carpathian Mountain Cabin',
    categoryId: 'cabins',
    roomType: 'Entire cabin',
    propertyType: 'Cabin',
    price: 126,
    smartLocation: 'Yaremche, Ukraine',
    city: 'Yaremche',
    country: 'Ukraine',
    neighborhood: 'Dora',
    latitude: 48.4514,
    longitude: 24.5541,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Mountain cabin with handcrafted wood details, fresh air, and a simple terrace for breakfast.',
  },
  {
    id: 'baku-boulevard-sky-suite',
    name: 'Baku Boulevard Sky Suite',
    categoryId: 'trending',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 156,
    smartLocation: 'Baku Boulevard, Azerbaijan',
    city: 'Baku',
    country: 'Azerbaijan',
    neighborhood: 'Seaside Boulevard',
    latitude: 40.3712,
    longitude: 49.8498,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    guests: 4,
    description: 'High-floor suite with Caspian views, a sleek living room, and quick access to the boulevard.',
  },
  {
    id: 'istanbul-galata-designer-flat',
    name: 'Galata Designer Flat',
    categoryId: 'trending',
    roomType: 'Entire flat',
    propertyType: 'Apartment',
    price: 142,
    smartLocation: 'Galata, Istanbul, Turkiye',
    city: 'Istanbul',
    country: 'Turkiye',
    neighborhood: 'Galata',
    latitude: 41.0256,
    longitude: 28.9742,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    guests: 4,
    description: 'Designer flat near Galata Tower with high ceilings, curated furniture, and lively streets outside.',
  },
  {
    id: 'dubai-marina-panorama',
    name: 'Dubai Marina Panorama',
    categoryId: 'trending',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 245,
    smartLocation: 'Dubai Marina, United Arab Emirates',
    city: 'Dubai',
    country: 'United Arab Emirates',
    neighborhood: 'Dubai Marina',
    latitude: 25.0803,
    longitude: 55.1403,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    guests: 5,
    description: 'Bright marina apartment with balcony views, building amenities, and a short walk to the waterfront.',
  },
  {
    id: 'paris-marais-loft',
    name: 'Marais Loft with Beams',
    categoryId: 'trending',
    roomType: 'Entire loft',
    propertyType: 'Loft',
    price: 218,
    smartLocation: 'Le Marais, Paris, France',
    city: 'Paris',
    country: 'France',
    neighborhood: 'Le Marais',
    latitude: 48.8575,
    longitude: 2.3585,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Character loft with exposed beams, thoughtful lighting, and cafes and galleries around the corner.',
  },
  {
    id: 'barcelona-eixample-terrace',
    name: 'Eixample Terrace Apartment',
    categoryId: 'trending',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 176,
    smartLocation: 'Eixample, Barcelona, Spain',
    city: 'Barcelona',
    country: 'Spain',
    neighborhood: 'Eixample',
    latitude: 41.3926,
    longitude: 2.1649,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Sunny apartment with a private terrace, patterned floors, and easy metro access across Barcelona.',
  },
  {
    id: 'london-shoreditch-warehouse',
    name: 'Shoreditch Warehouse Loft',
    categoryId: 'trending',
    roomType: 'Entire loft',
    propertyType: 'Loft',
    price: 232,
    smartLocation: 'Shoreditch, London, United Kingdom',
    city: 'London',
    country: 'United Kingdom',
    neighborhood: 'Shoreditch',
    latitude: 51.5245,
    longitude: -0.0762,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    guests: 4,
    description: 'Warehouse loft with exposed brick, oversized windows, and quick walks to markets and nightlife.',
  },
  {
    id: 'rome-trastevere-rooftop',
    name: 'Trastevere Rooftop Apartment',
    categoryId: 'trending',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 185,
    smartLocation: 'Trastevere, Rome, Italy',
    city: 'Rome',
    country: 'Italy',
    neighborhood: 'Trastevere',
    latitude: 41.8896,
    longitude: 12.4707,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    guests: 4,
    description: 'Warm apartment with rooftop access, terracotta colors, and classic trattorias nearby.',
  },
  {
    id: 'lisbon-alfama-sun-apartment',
    name: 'Alfama Sun Apartment',
    categoryId: 'trending',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 149,
    smartLocation: 'Alfama, Lisbon, Portugal',
    city: 'Lisbon',
    country: 'Portugal',
    neighborhood: 'Alfama',
    latitude: 38.7139,
    longitude: -9.1294,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Sunlit apartment on a quiet stair street with tile details and river glimpses from the window.',
  },
  {
    id: 'athens-acropolis-view-suite',
    name: 'Acropolis View Suite',
    categoryId: 'trending',
    roomType: 'Entire suite',
    propertyType: 'Apartment',
    price: 168,
    smartLocation: 'Plaka, Athens, Greece',
    city: 'Athens',
    country: 'Greece',
    neighborhood: 'Plaka',
    latitude: 37.9726,
    longitude: 23.728,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Stylish suite with balcony seating, warm stone accents, and Acropolis views from the neighborhood.',
  },
  {
    id: 'baku-game-loft',
    name: 'Baku Game Loft',
    categoryId: 'play',
    roomType: 'Entire loft',
    propertyType: 'Loft',
    price: 121,
    smartLocation: 'Nizami Street, Baku, Azerbaijan',
    city: 'Baku',
    country: 'Azerbaijan',
    neighborhood: 'Nizami',
    latitude: 40.3749,
    longitude: 49.8396,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Loft made for friend trips with a gaming corner, smart TV, board games, and central food spots nearby.',
  },
  {
    id: 'istanbul-music-studio-home',
    name: 'Istanbul Music Studio Home',
    categoryId: 'play',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 135,
    smartLocation: 'Kadikoy, Istanbul, Turkiye',
    city: 'Istanbul',
    country: 'Turkiye',
    neighborhood: 'Kadikoy',
    latitude: 40.9905,
    longitude: 29.0254,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    guests: 4,
    description: 'Creative apartment with a small music corner, vinyl shelves, and easy access to cafes and ferries.',
  },
  {
    id: 'barcelona-padel-penthouse',
    name: 'Barcelona Padel Penthouse',
    categoryId: 'play',
    roomType: 'Entire penthouse',
    propertyType: 'Penthouse',
    price: 202,
    smartLocation: 'Poblenou, Barcelona, Spain',
    city: 'Barcelona',
    country: 'Spain',
    neighborhood: 'Poblenou',
    latitude: 41.4036,
    longitude: 2.2035,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    description: 'Penthouse for active stays with a sunny terrace, beach routes, and padel clubs close by.',
  },
  {
    id: 'dubai-arcade-family-suite',
    name: 'Dubai Arcade Family Suite',
    categoryId: 'play',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 228,
    smartLocation: 'Downtown Dubai, United Arab Emirates',
    city: 'Dubai',
    country: 'United Arab Emirates',
    neighborhood: 'Downtown',
    latitude: 25.1975,
    longitude: 55.2744,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 7,
    description: 'Family-friendly suite with arcade games, skyline views, a pool, and quick access to downtown attractions.',
  },
  {
    id: 'lisbon-surf-and-play-house',
    name: 'Lisbon Surf and Play House',
    categoryId: 'play',
    roomType: 'Entire house',
    propertyType: 'Townhouse',
    price: 157,
    smartLocation: 'Costa da Caparica, Lisbon, Portugal',
    city: 'Lisbon',
    country: 'Portugal',
    neighborhood: 'Costa da Caparica',
    latitude: 38.6447,
    longitude: -9.2361,
    bedrooms: 3,
    beds: 5,
    bathrooms: 2,
    guests: 8,
    description: 'Beach-town house with surf storage, games for rainy evenings, and space for a group dinner.',
  },
  {
    id: 'tbilisi-art-studio-loft',
    name: 'Tbilisi Art Studio Loft',
    categoryId: 'play',
    roomType: 'Entire loft',
    propertyType: 'Loft',
    price: 104,
    smartLocation: 'Vera, Tbilisi, Georgia',
    city: 'Tbilisi',
    country: 'Georgia',
    neighborhood: 'Vera',
    latitude: 41.7076,
    longitude: 44.7867,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Art studio loft with a work table, playful decor, and a relaxed neighborhood full of small bars.',
  },
  {
    id: 'batumi-boardwalk-game-flat',
    name: 'Batumi Boardwalk Game Flat',
    categoryId: 'play',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 112,
    smartLocation: 'Batumi Boulevard, Georgia',
    city: 'Batumi',
    country: 'Georgia',
    neighborhood: 'Boulevard',
    latitude: 41.6461,
    longitude: 41.6325,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Sea-air apartment with a console setup, balcony seating, and the boardwalk just outside.',
  },
  {
    id: 'prague-cinema-loft',
    name: 'Prague Cinema Loft',
    categoryId: 'play',
    roomType: 'Entire loft',
    propertyType: 'Loft',
    price: 146,
    smartLocation: 'Karlin, Prague, Czechia',
    city: 'Prague',
    country: 'Czechia',
    neighborhood: 'Karlin',
    latitude: 50.0911,
    longitude: 14.4516,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    guests: 4,
    description: 'Cinema-style loft with projector wall, comfortable seating, and quick tram links to old town.',
  },
  {
    id: 'baku-nizami-modern-apartment',
    name: 'Nizami Modern Apartment',
    categoryId: 'city',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 98,
    smartLocation: 'Nizami Street, Baku, Azerbaijan',
    city: 'Baku',
    country: 'Azerbaijan',
    neighborhood: 'Nizami',
    latitude: 40.376,
    longitude: 49.841,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    guests: 4,
    description: 'Modern city apartment with a comfortable living room, walkable cafes, and quick access to metro stations.',
  },
  {
    id: 'new-york-soho-sky-flat',
    name: 'SoHo Sky Flat',
    categoryId: 'city',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 295,
    smartLocation: 'SoHo, New York, United States',
    city: 'New York',
    country: 'United States',
    neighborhood: 'SoHo',
    latitude: 40.7248,
    longitude: -74.0018,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Bright SoHo flat with city views, clean design, and shopping and galleries just outside.',
  },
  {
    id: 'london-kensington-townhouse',
    name: 'Kensington Townhouse Flat',
    categoryId: 'city',
    roomType: 'Entire flat',
    propertyType: 'Townhouse flat',
    price: 255,
    smartLocation: 'Kensington, London, United Kingdom',
    city: 'London',
    country: 'United Kingdom',
    neighborhood: 'Kensington',
    latitude: 51.501,
    longitude: -0.191,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    guests: 4,
    description: 'Classic townhouse flat with elegant rooms, a quiet street, and museums and parks nearby.',
  },
  {
    id: 'paris-saint-germain-studio',
    name: 'Saint Germain Studio',
    categoryId: 'city',
    roomType: 'Entire studio',
    propertyType: 'Studio',
    price: 198,
    smartLocation: 'Saint Germain, Paris, France',
    city: 'Paris',
    country: 'France',
    neighborhood: 'Saint Germain',
    latitude: 48.8546,
    longitude: 2.3334,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Polished studio with soft colors, a small work desk, and bookstores and bakeries around the corner.',
  },
  {
    id: 'milan-brera-design-apartment',
    name: 'Brera Design Apartment',
    categoryId: 'city',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 184,
    smartLocation: 'Brera, Milan, Italy',
    city: 'Milan',
    country: 'Italy',
    neighborhood: 'Brera',
    latitude: 45.4719,
    longitude: 9.1878,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Design-forward apartment with warm lighting, a practical kitchen, and Milan galleries nearby.',
  },
  {
    id: 'vienna-central-altbau',
    name: 'Vienna Central Altbau',
    categoryId: 'city',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 164,
    smartLocation: 'Innere Stadt, Vienna, Austria',
    city: 'Vienna',
    country: 'Austria',
    neighborhood: 'Innere Stadt',
    latitude: 48.2088,
    longitude: 16.3716,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    guests: 4,
    description: 'High-ceiling city apartment with classic details, modern kitchen, and central sights within walking distance.',
  },
  {
    id: 'berlin-mitte-loft',
    name: 'Berlin Mitte Loft',
    categoryId: 'city',
    roomType: 'Entire loft',
    propertyType: 'Loft',
    price: 171,
    smartLocation: 'Mitte, Berlin, Germany',
    city: 'Berlin',
    country: 'Germany',
    neighborhood: 'Mitte',
    latitude: 52.5206,
    longitude: 13.4098,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    guests: 4,
    description: 'Open-plan loft with concrete details, soft textiles, and easy access to galleries and transport.',
  },
  {
    id: 'tokyo-shibuya-city-pad',
    name: 'Shibuya City Pad',
    categoryId: 'city',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 207,
    smartLocation: 'Shibuya, Tokyo, Japan',
    city: 'Tokyo',
    country: 'Japan',
    neighborhood: 'Shibuya',
    latitude: 35.6595,
    longitude: 139.7005,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Compact city pad with smart storage, clean interiors, and Shibuya energy right outside.',
  },
  {
    id: 'singapore-orchard-condo',
    name: 'Orchard Calm Condo',
    categoryId: 'city',
    roomType: 'Entire condo',
    propertyType: 'Condo',
    price: 224,
    smartLocation: 'Orchard, Singapore',
    city: 'Singapore',
    country: 'Singapore',
    neighborhood: 'Orchard',
    latitude: 1.3048,
    longitude: 103.8318,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    guests: 4,
    description: 'Calm condo with building amenities, a practical kitchen, and shopping and dining close by.',
  },
  {
    id: 'bilgah-sea-view-villa',
    name: 'Bilgah Sea View Villa',
    categoryId: 'beachfront',
    roomType: 'Entire villa',
    propertyType: 'Villa',
    price: 215,
    smartLocation: 'Bilgah, Baku, Azerbaijan',
    city: 'Baku',
    country: 'Azerbaijan',
    neighborhood: 'Bilgah',
    latitude: 40.5908,
    longitude: 50.0388,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    guests: 9,
    description: 'Sea-view villa with a private garden, outdoor dining, and quick access to Absheron beaches.',
  },
  {
    id: 'batumi-beachfront-apartment',
    name: 'Batumi Beachfront Apartment',
    categoryId: 'beachfront',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 129,
    smartLocation: 'Batumi Beach, Georgia',
    city: 'Batumi',
    country: 'Georgia',
    neighborhood: 'New Boulevard',
    latitude: 41.6309,
    longitude: 41.6006,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Beachfront apartment with a wide balcony, sea breeze, and restaurants along the promenade.',
  },
  {
    id: 'bodrum-white-villa',
    name: 'Bodrum White Villa',
    categoryId: 'beachfront',
    roomType: 'Entire villa',
    propertyType: 'Villa',
    price: 292,
    smartLocation: 'Bodrum, Turkiye',
    city: 'Bodrum',
    country: 'Turkiye',
    neighborhood: 'Yalikavak',
    latitude: 37.1059,
    longitude: 27.2861,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    guests: 8,
    description: 'Whitewashed villa with a pool, shaded terrace, and relaxed Aegean style minutes from the marina.',
  },
  {
    id: 'antalya-konyaalti-flat',
    name: 'Konyaalti Beach Flat',
    categoryId: 'beachfront',
    roomType: 'Entire flat',
    propertyType: 'Apartment',
    price: 138,
    smartLocation: 'Konyaalti, Antalya, Turkiye',
    city: 'Antalya',
    country: 'Turkiye',
    neighborhood: 'Konyaalti',
    latitude: 36.8631,
    longitude: 30.636,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Fresh beach flat with mountain glimpses, a balcony, and a straight walk to the shoreline.',
  },
  {
    id: 'barcelona-beach-studio',
    name: 'Barcelona Beach Studio',
    categoryId: 'beachfront',
    roomType: 'Entire studio',
    propertyType: 'Studio',
    price: 154,
    smartLocation: 'Barceloneta, Barcelona, Spain',
    city: 'Barcelona',
    country: 'Spain',
    neighborhood: 'Barceloneta',
    latitude: 41.3796,
    longitude: 2.1897,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    description: 'Easy beach studio with clean interiors, a practical kitchenette, and sand and tapas streets nearby.',
  },
  {
    id: 'amalfi-cliffside-suite',
    name: 'Amalfi Cliffside Suite',
    categoryId: 'beachfront',
    roomType: 'Entire suite',
    propertyType: 'Suite',
    price: 276,
    smartLocation: 'Amalfi Coast, Italy',
    city: 'Amalfi',
    country: 'Italy',
    neighborhood: 'Atrani',
    latitude: 40.6368,
    longitude: 14.6085,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 3,
    description: 'Cliffside suite with sea-facing windows, a small terrace, and coastal paths close by.',
  },
  {
    id: 'bali-canggu-pool-villa',
    name: 'Canggu Pool Villa',
    categoryId: 'beachfront',
    roomType: 'Entire villa',
    propertyType: 'Villa',
    price: 188,
    smartLocation: 'Canggu, Bali, Indonesia',
    city: 'Canggu',
    country: 'Indonesia',
    neighborhood: 'Berawa',
    latitude: -8.6507,
    longitude: 115.1387,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    guests: 6,
    description: 'Tropical villa with a private pool, open living space, and beaches and cafes nearby.',
  },
  {
    id: 'dubai-jumeirah-beach-residence',
    name: 'Jumeirah Beach Residence',
    categoryId: 'beachfront',
    roomType: 'Entire apartment',
    propertyType: 'Apartment',
    price: 248,
    smartLocation: 'JBR, Dubai, United Arab Emirates',
    city: 'Dubai',
    country: 'United Arab Emirates',
    neighborhood: 'JBR',
    latitude: 25.0786,
    longitude: 55.1332,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    guests: 5,
    description: 'Beach residence with sea views, a modern kitchen, pool access, and restaurants downstairs.',
  },
  {
    id: 'shamakhi-vineyard-house',
    name: 'Shamakhi Vineyard House',
    categoryId: 'countryside',
    roomType: 'Entire house',
    propertyType: 'Country house',
    price: 124,
    smartLocation: 'Shamakhi, Azerbaijan',
    city: 'Shamakhi',
    country: 'Azerbaijan',
    neighborhood: 'Meysari',
    latitude: 40.6319,
    longitude: 48.6414,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 7,
    description: 'Countryside house near vineyards with open views, a garden table, and quiet evenings under the stars.',
  },
  {
    id: 'kakheti-wine-country-home',
    name: 'Kakheti Wine Country Home',
    categoryId: 'countryside',
    roomType: 'Entire home',
    propertyType: 'Country house',
    price: 118,
    smartLocation: 'Telavi, Kakheti, Georgia',
    city: 'Telavi',
    country: 'Georgia',
    neighborhood: 'Tsinandali',
    latitude: 41.8931,
    longitude: 45.5692,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 7,
    description: 'Wine country home with a shaded courtyard, rustic kitchen, and mountain silhouettes in the distance.',
  },
  {
    id: 'tuscany-stone-farmhouse',
    name: 'Tuscany Stone Farmhouse',
    categoryId: 'countryside',
    roomType: 'Entire farmhouse',
    propertyType: 'Farmhouse',
    price: 236,
    smartLocation: 'Val d Orcia, Tuscany, Italy',
    city: 'Pienza',
    country: 'Italy',
    neighborhood: 'Val d Orcia',
    latitude: 43.0766,
    longitude: 11.6792,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    guests: 8,
    description: 'Stone farmhouse with rolling hill views, outdoor dining, and a warm kitchen for long dinners.',
  },
  {
    id: 'provence-lavender-cottage',
    name: 'Provence Lavender Cottage',
    categoryId: 'countryside',
    roomType: 'Entire cottage',
    propertyType: 'Cottage',
    price: 174,
    smartLocation: 'Luberon, Provence, France',
    city: 'Gordes',
    country: 'France',
    neighborhood: 'Luberon',
    latitude: 43.9123,
    longitude: 5.2004,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 4,
    description: 'Lavender-country cottage with stone walls, a sunny patio, and peaceful village roads nearby.',
  },
  {
    id: 'alps-meadow-chalet',
    name: 'Alps Meadow Chalet',
    categoryId: 'countryside',
    roomType: 'Entire chalet',
    propertyType: 'Chalet',
    price: 221,
    smartLocation: 'Interlaken, Switzerland',
    city: 'Interlaken',
    country: 'Switzerland',
    neighborhood: 'Wilderswil',
    latitude: 46.6635,
    longitude: 7.8611,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    description: 'Meadow chalet with alpine views, wood interiors, and hiking trails close to the front door.',
  },
  {
    id: 'lake-como-village-home',
    name: 'Lake Como Village Home',
    categoryId: 'countryside',
    roomType: 'Entire home',
    propertyType: 'Village home',
    price: 207,
    smartLocation: 'Varenna, Lake Como, Italy',
    city: 'Varenna',
    country: 'Italy',
    neighborhood: 'Varenna',
    latitude: 46.0112,
    longitude: 9.2832,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 5,
    description: 'Village home with lake glimpses, stone steps nearby, and a calm terrace for morning coffee.',
  },
  {
    id: 'english-cotswold-cottage',
    name: 'Cotswold Honey-Stone Cottage',
    categoryId: 'countryside',
    roomType: 'Entire cottage',
    propertyType: 'Cottage',
    price: 192,
    smartLocation: 'Bibury, Cotswolds, United Kingdom',
    city: 'Bibury',
    country: 'United Kingdom',
    neighborhood: 'Bibury',
    latitude: 51.7587,
    longitude: -1.833,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 4,
    description: 'Honey-stone cottage with garden seating, low beams, and classic village walks nearby.',
  },
  {
    id: 'norwegian-fjord-farmhouse',
    name: 'Norwegian Fjord Farmhouse',
    categoryId: 'countryside',
    roomType: 'Entire farmhouse',
    propertyType: 'Farmhouse',
    price: 214,
    smartLocation: 'Aurland, Norway',
    city: 'Aurland',
    country: 'Norway',
    neighborhood: 'Aurlandsfjord',
    latitude: 60.9088,
    longitude: 7.1907,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    description: 'Fjord farmhouse with wide views, simple Nordic interiors, and peaceful roads for scenic drives.',
  },
];

const makeHostName = (owner: DemoOwner) =>
  [owner.first_name, owner.last_name].filter(Boolean).join(' ') || owner.email || 'Host';

const makeImageUrls = (listingIndex: number) => [...demoListingImageSets[listingIndex % demoListingImageSets.length]];

export const buildDemoListings = (owners: DemoOwner[]) =>
  demoTemplates.map((template, index) => {
    const owner = owners[index % owners.length];
    const imageUrls = makeImageUrls(index);
    const amenities = amenitySets[index % amenitySets.length];

    return {
      id: `demo-home-${template.id}`,
      name: template.name,
      status: 'accepted' as const,
      category_id: template.categoryId,
      owner_user_id: owner.id,
      owner_email: owner.email,
      host_name: makeHostName(owner),
      room_type: template.roomType,
      property_type: template.propertyType,
      price: template.price,
      smart_location: template.smartLocation,
      address: template.smartLocation,
      city: template.city,
      country: template.country,
      neighbourhood: template.neighborhood,
      neighborhood: template.neighborhood,
      neighborhood_overview: `${template.neighborhood} is a practical base in ${template.city}, close to local food spots, walks, and transport.`,
      latitude: template.latitude,
      longitude: template.longitude,
      bedrooms: template.bedrooms,
      beds: template.beds,
      bathrooms: template.bathrooms,
      guests_included: template.guests,
      accommodates: template.guests,
      amenities,
      description: template.description,
      image_urls: imageUrls,
      cloudinary_public_ids: [],
      medium_url: imageUrls[0],
      xl_picture_url: imageUrls[0],
      review_scores_rating: 0,
      number_of_reviews: 0,
      instant_bookable: true,
      cancellation_policy: 'moderate',
      minimum_nights: 1,
      maximum_nights: 30,
    };
  });
